# Generated by Django 5.1.2 on 2024-10-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('book_type', models.CharField(max_length=50)),
                ('img', models.ImageField(default='book_images/default.png', upload_to='book_images/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
